spring.application.name=live-chat-backend

# ===============================
# Aiven MySQL Database
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# File Upload
# ===============================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=uploads

# ===============================
# Render Server
# ===============================

server.address=0.0.0.0


# ===============================
# Actuator
# ===============================

management.endpoints.web.exposure.include=health,mappings
management.endpoint.health.show-details=always
management.health.db.enabled=true